Extension { #name : #FAMIXType }

{ #category : #'*OrionFamixCore-Class' }
FAMIXType >> privateAttributes [
	^ attributes
]

{ #category : #'*OrionFamixCore-Class' }
FAMIXType >> privateAttributes: aAttribute [
	 attributes := aAttribute
]

{ #category : #'*OrionFamixCore-Class' }
FAMIXType >> privateBehavioursWithDeclaredType [
	^ behavioursWithDeclaredType
]

{ #category : #'*OrionFamixCore-Class' }
FAMIXType >> privateBehavioursWithDeclaredType: aBehaviouralEntity [
	 behavioursWithDeclaredType := aBehaviouralEntity
]

{ #category : #'*OrionFamixCore-Class' }
FAMIXType >> privateContainer [
	^ container
]

{ #category : #'*OrionFamixCore-Class' }
FAMIXType >> privateContainer: aContainerEntity [
	 container := aContainerEntity
]

{ #category : #'*OrionFamixCore-Class' }
FAMIXType >> privateIncomingReferences [
	^ incomingReferences
]

{ #category : #'*OrionFamixCore-Class' }
FAMIXType >> privateIncomingReferences: aReference [
	 incomingReferences := aReference
]

{ #category : #'*OrionFamixCore-Class' }
FAMIXType >> privateMethods [
	^ methods
]

{ #category : #'*OrionFamixCore-Class' }
FAMIXType >> privateMethods: aMethod [
	 methods := aMethod
]

{ #category : #'*OrionFamixCore-Class' }
FAMIXType >> privateStructuresWithDeclaredType [
	^ structuresWithDeclaredType
]

{ #category : #'*OrionFamixCore-Class' }
FAMIXType >> privateStructuresWithDeclaredType: aStructuralEntity [
	 structuresWithDeclaredType := aStructuralEntity
]

{ #category : #'*OrionFamixCore-Class' }
FAMIXType >> privateSubInheritances [
	^ subInheritances
]

{ #category : #'*OrionFamixCore-Class' }
FAMIXType >> privateSubInheritances: aInheritance [
	 subInheritances := aInheritance
]

{ #category : #'*OrionFamixCore-Class' }
FAMIXType >> privateSuperInheritances [
	^ superInheritances
]

{ #category : #'*OrionFamixCore-Class' }
FAMIXType >> privateSuperInheritances: aInheritance [
	 superInheritances := aInheritance
]
