Extension { #name : #FAMIXInheritance }

{ #category : #'*OrionFamixCore-Class' }
FAMIXInheritance >> privateSubclass [
	^ subclass
]

{ #category : #'*OrionFamixCore-Class' }
FAMIXInheritance >> privateSubclass: aType [
	 subclass := aType
]

{ #category : #'*OrionFamixCore-Class' }
FAMIXInheritance >> privateSuperclass [
	^ superclass
]

{ #category : #'*OrionFamixCore-Class' }
FAMIXInheritance >> privateSuperclass: aType [
	 superclass := aType
]
