Extension { #name : #FAMIXFunction }

{ #category : #'*OrionFamixCore-Class' }
FAMIXFunction >> privateContainer [
	^ container
]

{ #category : #'*OrionFamixCore-Class' }
FAMIXFunction >> privateContainer: aContainerEntity [
	 container := aContainerEntity
]

{ #category : #'*OrionFamixCore-Class' }
FAMIXFunction >> privateFunctions [
	^ functions
]

{ #category : #'*OrionFamixCore-Class' }
FAMIXFunction >> privateFunctions: aFunction [
	 functions := aFunction
]
