Extension { #name : #FAMIXContainerEntity }

{ #category : #'*OrionFamixCore-Class' }
FAMIXContainerEntity >> privateFunctions [
	^ functions
]

{ #category : #'*OrionFamixCore-Class' }
FAMIXContainerEntity >> privateFunctions: aFAMIXFunction [
	 functions := aFAMIXFunction
]

{ #category : #'*OrionFamixCore-Class' }
FAMIXContainerEntity >> privateTypes [
	^ types
]

{ #category : #'*OrionFamixCore-Class' }
FAMIXContainerEntity >> privateTypes: aType [
	 types := aType
]
