Extension { #name : #FAMIXAttribute }

{ #category : #'*OrionFamixCore-Class' }
FAMIXAttribute >> privateHasClassScope [
	^ hasClassScope
]

{ #category : #'*OrionFamixCore-Class' }
FAMIXAttribute >> privateHasClassScope: aBoolean [
	 hasClassScope := aBoolean
]

{ #category : #'*OrionFamixCore-Class' }
FAMIXAttribute >> privateParentType [
	^ parentType
]

{ #category : #'*OrionFamixCore-Class' }
FAMIXAttribute >> privateParentType: aType [
	 parentType := aType
]
