Extension { #name : #FAMIXAnnotationTypeAttribute }

{ #category : #'*OrionFamixCore-Class' }
FAMIXAnnotationTypeAttribute >> privateAnnotationAttributeInstances [
	^ annotationAttributeInstances
]

{ #category : #'*OrionFamixCore-Class' }
FAMIXAnnotationTypeAttribute >> privateAnnotationAttributeInstances: aAnnotationInstanceAttribute [
	 annotationAttributeInstances := aAnnotationInstanceAttribute
]
