"
A ORActionRemoveFAMIXAnnotationInstanceAttribute is a generated class useful to Orion. It corresponds to an action that can be performed on a type of model element 
"
Class {
	#name : #ORActionRemoveAnnotationInstanceAttribute,
	#superclass : #ORActionRemove,
	#category : #'OrionFamixCore-Action'
}

{ #category : #'method execution' }
ORActionRemoveAnnotationInstanceAttribute >> run [
	self shouldBeImplemented
]
