"
A ORActionMoveAnnotationInstanceAttribute is a generated class useful to Orion. It corresponds to an action that can be performed on a type of model element. See OrionGenerator in Moose/Orion on SmalltalkHub for more information.
"
Class {
	#name : #ORActionMoveAnnotationInstanceAttribute,
	#superclass : #ORActionMove,
	#category : #'OrionFamixCore-Action'
}

{ #category : #'method execution' }
ORActionMoveAnnotationInstanceAttribute >> run [
	self shouldBeImplemented
]
