"
A ORActionAddFAMIXAnnotationInstanceAttribute is a generated class useful to Orion. It corresponds to an action that can be performed on a type of model element 
"
Class {
	#name : #ORActionAddnnotationInstanceAttribute,
	#superclass : #ORActionAddEntity,
	#category : #'OrionFamixCore-Action'
}

{ #category : #'method execution' }
ORActionAddnnotationInstanceAttribute >> run [
	self shouldBeImplemented
]
