Extension { #name : #FAMIXComment }

{ #category : #'*OrionCore-model' }
FAMIXComment >> privateContainer [
	^ container
]

{ #category : #'*OrionCore-model' }
FAMIXComment >> privateContainer: aContainer [
	container := aContainer
]

{ #category : #'*OrionCore-model' }
FAMIXComment >> privateContentString [
	^ contentString
]

{ #category : #'*OrionCore-model' }
FAMIXComment >> privateContentString: aString [
	contentString := aString
]
