Extension { #name : #FAMIXFileAnchor }

{ #category : #'*OrionCore-model' }
FAMIXFileAnchor >> privateEndColumn [
	^ endColumn
]

{ #category : #'*OrionCore-model' }
FAMIXFileAnchor >> privateEndColumn: anObject [
	endColumn := anObject
]

{ #category : #'*OrionCore-model' }
FAMIXFileAnchor >> privateEndLine [
	^ endLine
]

{ #category : #'*OrionCore-model' }
FAMIXFileAnchor >> privateEndLine: anObject [
	endLine := anObject
]

{ #category : #'*OrionCore-model' }
FAMIXFileAnchor >> privateFileName [
	^ fileName
]

{ #category : #'*OrionCore-model' }
FAMIXFileAnchor >> privateFileName: anObject [
	fileName := anObject
]

{ #category : #'*OrionCore-model' }
FAMIXFileAnchor >> privateStartColumn [
	^ startColumn
]

{ #category : #'*OrionCore-model' }
FAMIXFileAnchor >> privateStartColumn: anObject [
	startColumn := anObject
]

{ #category : #'*OrionCore-model' }
FAMIXFileAnchor >> privateStartLine [
	^ startLine
]

{ #category : #'*OrionCore-model' }
FAMIXFileAnchor >> privateStartLine: anObject [
	startLine := anObject
]
