Extension { #name : #FAMIXInheritance }

{ #category : #'*OrionCore-model' }
FAMIXInheritance >> privateSubclass [
	^subclass
]

{ #category : #'*OrionCore-model' }
FAMIXInheritance >> privateSubclass: aType [
	subclass := aType
]

{ #category : #'*OrionCore-model' }
FAMIXInheritance >> privateSuperclass [
	
	^superclass
]

{ #category : #'*OrionCore-model' }
FAMIXInheritance >> privateSuperclass: aType [
	superclass := aType
]
