Extension { #name : #FAMIXFunction }

{ #category : #'*OrionCore-model' }
FAMIXFunction >> privateFunctions [
	^ functions
]

{ #category : #'*OrionCore-model' }
FAMIXFunction >> privateFunctions: aFunction [
	 functions := aFunction
]

{ #category : #'*OrionCore-model' }
FAMIXFunction >> privateParentScope [
	^ parentScope
]

{ #category : #'*OrionCore-model' }
FAMIXFunction >> privateParentScope: aFunction [
	 parentScope := aFunction
]
