Extension { #name : #FAMIXIndexedFileAnchor }

{ #category : #'*OrionFamixSourceAnchor-Class' }
FAMIXIndexedFileAnchor >> privateEndPos [
	^ endPos
]

{ #category : #'*OrionFamixSourceAnchor-Class' }
FAMIXIndexedFileAnchor >> privateEndPos: aNumber [
	endPos := aNumber
]

{ #category : #'*OrionFamixSourceAnchor-Class' }
FAMIXIndexedFileAnchor >> privateStartPos [
	^ startPos
]

{ #category : #'*OrionFamixSourceAnchor-Class' }
FAMIXIndexedFileAnchor >> privateStartPos: aNumber [
	startPos := aNumber
]
