Extension { #name : #FAMIXFileAnchor }

{ #category : #'*OrionFamixSourceAnchor-Class' }
FAMIXFileAnchor >> privateEndColumn [
	^ endColumn
]

{ #category : #'*OrionFamixSourceAnchor-Class' }
FAMIXFileAnchor >> privateEndColumn: aNumber [
	endColumn := aNumber
]

{ #category : #'*OrionFamixSourceAnchor-Class' }
FAMIXFileAnchor >> privateEndLine [
	^ endLine
]

{ #category : #'*OrionFamixSourceAnchor-Class' }
FAMIXFileAnchor >> privateEndLine: aNumber [
	endLine := aNumber
]

{ #category : #'*OrionFamixSourceAnchor-Class' }
FAMIXFileAnchor >> privateStartColumn [
	^ startColumn
]

{ #category : #'*OrionFamixSourceAnchor-Class' }
FAMIXFileAnchor >> privateStartColumn: aNumber [
	startColumn := aNumber
]

{ #category : #'*OrionFamixSourceAnchor-Class' }
FAMIXFileAnchor >> privateStartLine [
	^ startLine
]

{ #category : #'*OrionFamixSourceAnchor-Class' }
FAMIXFileAnchor >> privateStartLine: aNumber [
	startLine := aNumber
]
