Extension { #name : #FAMIXSourcedEntity }

{ #category : #'*OrionCore-model' }
FAMIXSourcedEntity >> privateComments [
	^ comments
]

{ #category : #'*OrionCore-model' }
FAMIXSourcedEntity >> privateComments: aComment [
	 comments := aComment
]

{ #category : #'*OrionCore-model' }
FAMIXSourcedEntity >> privateDeclaredSourceLanguage [
	^ declaredSourceLanguage
]

{ #category : #'*OrionCore-model' }
FAMIXSourcedEntity >> privateDeclaredSourceLanguage: aSourceLanguage [
	 declaredSourceLanguage := aSourceLanguage
]

{ #category : #'*OrionCore-model' }
FAMIXSourcedEntity >> privateSourceAnchor [
	^ sourceAnchor
]

{ #category : #'*OrionCore-model' }
FAMIXSourcedEntity >> privateSourceAnchor: aSourceAnchor [
	 sourceAnchor := aSourceAnchor
]
