Extension { #name : #FAMIXReference }

{ #category : #'*OrionCore-model' }
FAMIXReference >> privateSource [
	^ source
]

{ #category : #'*OrionCore-model' }
FAMIXReference >> privateSource: aContainerEntity [
	 source := aContainerEntity
]

{ #category : #'*OrionCore-model' }
FAMIXReference >> privateTarget [
	^ target
]

{ #category : #'*OrionCore-model' }
FAMIXReference >> privateTarget: aContainerEntity [
	 target := aContainerEntity
]
