Extension { #name : #FAMIXBehaviouralEntity }

{ #category : #'*OrionCore-model' }
FAMIXBehaviouralEntity >> privateAccesses [
	^ accesses
]

{ #category : #'*OrionCore-model' }
FAMIXBehaviouralEntity >> privateAccesses: aAccess [
	 accesses := aAccess
]

{ #category : #'*OrionCore-model' }
FAMIXBehaviouralEntity >> privateDeclaredType [
	^ declaredType
]

{ #category : #'*OrionCore-model' }
FAMIXBehaviouralEntity >> privateDeclaredType: aType [
	 declaredType := aType
]

{ #category : #'*OrionCore-model' }
FAMIXBehaviouralEntity >> privateImplicitVariables [
	^ implicitVariables
]

{ #category : #'*OrionCore-model' }
FAMIXBehaviouralEntity >> privateImplicitVariables: aImplicitVariable [
	 implicitVariables := aImplicitVariable
]

{ #category : #'*OrionCore-model' }
FAMIXBehaviouralEntity >> privateIncomingInvocations [
	^ incomingInvocations
]

{ #category : #'*OrionCore-model' }
FAMIXBehaviouralEntity >> privateIncomingInvocations: aInvocation [
	 incomingInvocations := aInvocation
]

{ #category : #'*OrionCore-model' }
FAMIXBehaviouralEntity >> privateLocalVariables [
	^ localVariables
]

{ #category : #'*OrionCore-model' }
FAMIXBehaviouralEntity >> privateLocalVariables: aLocalVariable [
	 localVariables := aLocalVariable
]

{ #category : #'*OrionCore-model' }
FAMIXBehaviouralEntity >> privateOutgoingInvocations [
	^ outgoingInvocations
]

{ #category : #'*OrionCore-model' }
FAMIXBehaviouralEntity >> privateOutgoingInvocations: aInvocation [
	 outgoingInvocations := aInvocation
]

{ #category : #'*OrionCore-model' }
FAMIXBehaviouralEntity >> privateParameters [
	^ parameters
]

{ #category : #'*OrionCore-model' }
FAMIXBehaviouralEntity >> privateParameters: aParameter [
	 parameters := aParameter
]

{ #category : #'*OrionCore-model' }
FAMIXBehaviouralEntity >> privateSignature [
	^ signature
]

{ #category : #'*OrionCore-model' }
FAMIXBehaviouralEntity >> privateSignature: aString [
	 signature := aString
]
